hWx(izvec,ixvec,:) =  MACB(1) * W(izvec,ixvec-3,:) ...
    + MACB(2) * W(izvec,ixvec-2,:) ...
    + MACB(3) * W(izvec,ixvec-1,:) ...
    + MACB(4) * W(izvec,ixvec  ,:) ...
    + MACB(5) * W(izvec,ixvec+1,:);
hWz(izvec,ixvec,:) =  MACB(1) * W(izvec-3,ixvec,:) ...
    + MACB(2) * W(izvec-2,ixvec,:) ...
    + MACB(3) * W(izvec-1,ixvec,:) ...
    + MACB(4) * W(izvec  ,ixvec,:) ...
    + MACB(5) * W(izvec+1,ixvec,:);

% hWx(4:end-3,4:end-3,:) =  MACB(1) * W(4:end-3,1:end-6 ,:) ...
%     +  MACB(2) * W(4:end-3,2:end-5,:) ...
%     +  MACB(3) * W(4:end-3,3:end-4,:) ...
%     +  MACB(4) * W(4:end-3,4:end-3,:) ...
%     +  MACB(5) * W(4:end-3,5:end-2,:);
% 
% 
% hWz(4:end-3,4:end-3,:) =  MACB(1) * W(1:end-6,4:end-3,:) ...
%     +  MACB(2) * W(2:end-5,4:end-3,:) ...
%     +  MACB(3) * W(3:end-4,4:end-3,:) ...
%     +  MACB(4) * W(4:end-3,4:end-3,:) ...
%     +  MACB(5) * W(5:end-2,4:end-3,:);


