hWz(izvec,ixvec,:) = CLT(1) * W(izvec-4,ixvec,:) ...
    + CLT(2) * W(izvec-3,ixvec,:) ...
    + CLT(3) * W(izvec-2,ixvec,:) ...
    + CLT(4) * W(izvec-1,ixvec,:) ...
    + CLT(5) * W(izvec  ,ixvec,:) ...
    + CLT(6) * W(izvec+1,ixvec,:) ...
    + CLT(7) * W(izvec+2,ixvec,:) ...
    + CLT(8) * W(izvec+3,ixvec,:) ...
    + CLT(9) * W(izvec+4,ixvec,:);

hWx(izvec,ixvec,:) = CLT(1) * W(izvec,ixvec-4,:) ...
    + CLT(2) * W(izvec,ixvec-3,:) ...
    + CLT(3) * W(izvec,ixvec-2,:) ...
    + CLT(4) * W(izvec,ixvec-1,:) ...
    + CLT(5) * W(izvec  ,ixvec,:) ...
    + CLT(6) * W(izvec,ixvec+1,:) ...
    + CLT(7) * W(izvec,ixvec+2,:) ...
    + CLT(8) * W(izvec,ixvec+3,:) ...
    + CLT(9) * W(izvec,ixvec+4,:);
