% -------------------------------------------------------------------------
% update for right hand side (rhs) derivatives; backward
%
%
% Author: Yuxing Pan (panyx2023@mail.sustech.edu.cn)
% Affiliation: Southern University of Science and Technology (SUSTech)
% Date: May 31, 2025
% -------------------------------------------------------------------------
%%%%%%
% inputs:
% x_grid : computational grid locations in x dimension --> 1D vector
% z_grid : computational grid locations in z dimension --> 1D vector
%

% nt : number of time step  --> 1D vector
% dt : length of time step  --> 1D vector

% Vs  : S wave velocity (km/s)  --> 2D array
% Vp  : P wave velocity (km/s)  --> 2D array
% rho : desity  (kg/m^3)  --> 2D array

% mu  : shear modulus       --> 2D array
% lam : Lamé parameter      --> 2D array
% lam2mu : λ + 2μ           --> 2D array


% outputs:
% Vx_t : x-direction velocity derivatives  --> 1D vector
% Vz_t : z-direction velocity derivatives  --> 1D vector

% Txx_t : xx direction Stress derivatives --> 2D array
% Tzz_t : zz direction Stress derivatives --> 2D array
% Txz_t : xz direction Stress derivatives --> 2D array

% mW : assmbled  time derivatives




%% inner point (RHS)
% assemble rhs

Vx=W(:,:,1);
Vz=W(:,:,2);
Txx=W(:,:,3);
Tzz=W(:,:,4);
Txz=W(:,:,5);



% Vx derivatives (Vx,xi ; Vx,zt)
Vx_xi(3:end-4,3:end-4) = (mac_all_coef{4}{2}(1).*Vx(4:end-3,1:end-6)...
    +mac_all_coef{4}{2}(2).*Vx(4:end-3,2:end-5)...
    +mac_all_coef{4}{2}(3).*Vx(4:end-3,3:end-4)...
    +mac_all_coef{4}{2}(4).*Vx(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Vx(4:end-3,5:end-2))  /   (xi_gd(2)-xi_gd(1))  ;
Vx_zt(3:end-4,3:end-4) = (mac_all_coef{4}{1}(1).*Vx(1:end-6,4:end-3)...
    +mac_all_coef{4}{2}(2).*Vx(2:end-5,4:end-3)...
    +mac_all_coef{4}{2}(3).*Vx(3:end-4,4:end-3)...
    +mac_all_coef{4}{2}(4).*Vx(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Vx(5:end-2,4:end-3))  /   (zt_gd(2)-zt_gd(1))  ;

% Vz derivatives (Vz,xi ; Vz,zt)
Vz_xi(3:end-4,3:end-4) = (mac_all_coef{4}{2}(1).*Vz(4:end-3,1:end-6)...
    +mac_all_coef{4}{2}(2).*Vz(4:end-3,2:end-5)...
    +mac_all_coef{4}{2}(3).*Vz(4:end-3,3:end-4)...
    +mac_all_coef{4}{2}(4).*Vz(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Vz(4:end-3,5:end-2))  /   (xi_gd(2)-xi_gd(1))  ;
Vz_zt(3:end-4,3:end-4) = (mac_all_coef{4}{1}(1).*Vz(1:end-6,4:end-3)...
    +mac_all_coef{4}{2}(2).*Vz(2:end-5,4:end-3)...
    +mac_all_coef{4}{2}(3).*Vz(3:end-4,4:end-3)...
    +mac_all_coef{4}{2}(4).*Vz(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Vz(5:end-2,4:end-3))  /   (zt_gd(2)-zt_gd(1))  ;
% Txx derivatives
Txx_xi(3:end-4,3:end-4) = (mac_all_coef{4}{2}(1).*Txx(4:end-3,1:end-6)...
    +mac_all_coef{4}{2}(2).*Txx(4:end-3,2:end-5)...
    +mac_all_coef{4}{2}(3).*Txx(4:end-3,3:end-4)...
    +mac_all_coef{4}{2}(4).*Txx(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Txx(4:end-3,5:end-2))  /   (xi_gd(2)-xi_gd(1))  ;
Txx_zt(3:end-4,3:end-4) = (mac_all_coef{4}{1}(1).*Txx(1:end-6,4:end-3)...
    +mac_all_coef{4}{2}(2).*Txx(2:end-5,4:end-3)...
    +mac_all_coef{4}{2}(3).*Txx(3:end-4,4:end-3)...
    +mac_all_coef{4}{2}(4).*Txx(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Txx(5:end-2,4:end-3))  /   (zt_gd(2)-zt_gd(1))  ;
% Tzz derivatives
Tzz_xi(3:end-4,3:end-4) = (mac_all_coef{4}{2}(1).*Tzz(4:end-3,1:end-6)...
    +mac_all_coef{4}{2}(2).*Tzz(4:end-3,2:end-5)...
    +mac_all_coef{4}{2}(3).*Tzz(4:end-3,3:end-4)...
    +mac_all_coef{4}{2}(4).*Tzz(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Tzz(4:end-3,5:end-2))  /   (xi_gd(2)-xi_gd(1))  ;
Tzz_zt(3:end-4,3:end-4) = (mac_all_coef{4}{1}(1).*Tzz(1:end-6,4:end-3)...
    +mac_all_coef{4}{2}(2).*Tzz(2:end-5,4:end-3)...
    +mac_all_coef{4}{2}(3).*Tzz(3:end-4,4:end-3)...
    +mac_all_coef{4}{2}(4).*Tzz(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Tzz(5:end-2,4:end-3))  /   (zt_gd(2)-zt_gd(1))  ;
% Txz derivatives
Txz_xi(3:end-4,3:end-4) = (mac_all_coef{4}{2}(1).*Txz(4:end-3,1:end-6)...
    +mac_all_coef{4}{2}(2).*Txz(4:end-3,2:end-5)...
    +mac_all_coef{4}{2}(3).*Txz(4:end-3,3:end-4)...
    +mac_all_coef{4}{2}(4).*Txz(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Txz(4:end-3,5:end-2))  /   (xi_gd(2)-xi_gd(1))  ;
Txz_zt(3:end-4,3:end-4) = (mac_all_coef{4}{1}(1).*Txz(1:end-6,4:end-3)...
    +mac_all_coef{4}{2}(2).*Txz(2:end-5,4:end-3)...
    +mac_all_coef{4}{2}(3).*Txz(3:end-4,4:end-3)...
    +mac_all_coef{4}{2}(4).*Txz(4:end-3,4:end-3)...
    +mac_all_coef{4}{2}(5).*Txz(5:end-2,4:end-3))  /   (zt_gd(2)-zt_gd(1))  ;



% for moment equation
Vx_t = (1./rho).*(xi_x.*Txx_xi + zt_x.*Txx_zt + xi_z.*Txz_xi + zt_z.*Txz_zt);
Vz_t = (1./rho).*(xi_x.*Txz_xi + zt_x.*Txz_zt + xi_z.*Tzz_xi + zt_z.*Tzz_zt);


% for Hooke's equatoinTzz_xi
Txx_t = lam2mu.*(xi_x.*Vx_xi) + lam2mu.*(zt_x.*Vx_zt)...
    +lam.*xi_z.*Vz_xi + lam.*zt_z.*Vz_zt    ;
Tzz_t = lam.*(xi_x.*Vx_xi) + lam.*(zt_x.*Vx_zt)...
    +lam2mu.*xi_z.*Vz_xi + lam2mu.*zt_z.*Vz_zt    ;
Txz_t = mu.*(xi_z.*Vx_xi + xi_x.*Vz_xi) + mu.*(zt_z.*Vx_zt + zt_x.*Vz_zt)  ;

% assemble rhs
W = cat(3, Vx, Vz, Txx, Tzz, Txz);

% assemble time derivative rhs
tdW = cat(3, Vx_t, Vz_t, Txx_t, Tzz_t, Txz_t);