hWz(izvec,ixvec,:) =  MACF(1) * W(izvec-1,ixvec,:) ...
    + MACF(2) * W(izvec  ,ixvec,:) ...
    + MACF(3) * W(izvec+1,ixvec,:) ...
    + MACF(4) * W(izvec+2,ixvec,:) ...
    + MACF(5) * W(izvec+3,ixvec,:);
hWx(izvec,ixvec,:) =  MACF(1) * W(izvec,ixvec-1,:) ...
    + MACF(2) * W(izvec,ixvec  ,:) ...
    + MACF(3) * W(izvec,ixvec+1,:) ...
    + MACF(4) * W(izvec,ixvec+2,:) ...
    + MACF(5) * W(izvec,ixvec+3,:);

% hWz(4:end-3,4:end-3,:) =  MACF(1) * W(3:end-4,4:end-3,:) ...
%     + MACF(2) * W(4:end-3,4:end-3,:) ...
%     + MACF(3) * W(5:end-2,4:end-3,:) ...
%     + MACF(4) * W(6:end-1,4:end-3,:) ...
%     + MACF(5) * W(7:end  ,4:end-3,:);
%
% hWx(4:end-3,4:end-3,:) =  MACF(1) * W(izvec,3:end-4,:) ...
%     + MACF(2) * W(izvec,4:end-3,:) ...
%     + MACF(3) * W(izvec,5:end-2,:) ...
%     + MACF(4) * W(izvec,6:end-1,:) ...
%     + MACF(5) * W(4:end-3,7:end,:);







