W(izvec,ixvec,:) = W(izvec,ixvec,:)- sigma*(FLT(1) * W(izvec-4,ixvec,:) ...
    + FLT(2) * W(izvec-3,ixvec,:) ...
    + FLT(3) * W(izvec-2,ixvec,:) ...
    + FLT(4) * W(izvec-1,ixvec,:) ...
    + FLT(5) * W(izvec  ,ixvec,:) ...
    + FLT(6) * W(izvec+1,ixvec,:) ...
    + FLT(7) * W(izvec+2,ixvec,:) ...
    + FLT(8) * W(izvec+3,ixvec,:) ...
    + FLT(9) * W(izvec+4,ixvec,:));
W(izvec,ixvec,:) = W(izvec,ixvec,:) - sigma*(FLT(1) * W(izvec,ixvec-4,:) ...
    + FLT(2) * W(izvec,ixvec-3,:) ...
    + FLT(3) * W(izvec,ixvec-2,:) ...
    + FLT(4) * W(izvec,ixvec-1,:) ...
    + FLT(5) * W(izvec  ,ixvec,:) ...
    + FLT(6) * W(izvec,ixvec+1,:) ...
    + FLT(7) * W(izvec,ixvec+2,:) ...
    + FLT(8) * W(izvec,ixvec+3,:) ...
    + FLT(9) * W(izvec,ixvec+4,:));
